on: [push]
jobs:
    prepare-env-job:
        runs-on: ubuntu-latest
        name: A job to prepare env variables
        steps:
            - uses: actions/checkout@v4
            - id: test
              uses: devikrishnamk0123/composite-actions-trial@dev
              with: 
                environment: dev
                branch:
                    main


