on: [push]
jobs:
    prepare-env-job:
        runs-on: ubuntu-latest
        name: A job to prepare env variables
        steps:
            - uses: actions/checkout@v4
            - id: prepare-env
              uses: devikrishnamk0123/composite-actions-trial/prepare-env@dev
              with: 
                environment: dev
                branch:
                    dev
            - run: |
                echo AWS ROLE - "$AWS_ROLE"
                echo ENV - "$ENV"
              env:
                AWS_ROLE: ${{ steps.prepare-env.outputs.AWS_ROLE }}
                ENV: ${{ steps.prepare-env.outputs.ENV }}
